#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tzsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

export STOW_FOLDERS=$STOW_FOLDERS 
export DOTFILES=$DOTFILES 
$DOTFILES/link
